
name: IRbady CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Init gradle wrapper 
        run: gradle wrapper --gradle-version 6.1.1
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - uses: actions/upload-artifact@v2
        with:
         name: Package
         path: app/build/outputs/apk/release/
         retention-days: 2
